# Generated by Django 3.0.8 on 2020-07-14 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200714_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
