# Generated by Django 3.0.8 on 2020-07-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200714_2146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watch',
            unique_together={('user', 'listing')},
        ),
    ]
